### ISSUE TITLE
Updated Korean font

### ISSUE THREAD

**Issue by DDinghoya** [JeffRuLz/OpenHCL#2]
Hi friend!

I want to replace the new font that satisfies the better readability and capacity compared to the previous Korean font.

Please see the attached file.

Best regards.

[font8x8-kr_갈무리M.zip](https://github.com/JeffRuLz/OpenHCL/files/5074635/font8x8-kr_.M.zip)

**Comment by JeffRuLz** [comment]
Hello. I've been picking away at this for a few days, but since I don't read Korean I am having difficulties deciding on a solution.

Is there a reason why this font is missing characters? For example 갂 and 갃
If the missing characters are not needed then I could use the preassembled characters in a separate image. 

If the missing characters are needed then there are too many of them. I will need a font where the jamo parts can be laid on top of each other to assemble a full character, like the first image you provided.

**Comment by DDinghoya** [comment]
> Hello. I've been picking away at this for a few days, but since I don't read Korean I am having difficulties deciding on a solution.
> 
> Is there a reason why this font is missing characters? For example 갂 and 갃
> If the missing characters are not needed then I could use the preassembled characters in a separate image.
> 
> If the missing characters are needed then there are too many of them. I will need a font where the jamo parts can be laid on top of each other to assemble a full character, like the first image you provided.

Although some missing, No problem missing font for OpenHCL.

this reason difference korean both completed and combination type.

Thank you for your strong support!

Best regard,

**Comment by JeffRuLz** [comment]
Added in v2020.08.26
